const info = [
  {
    id: 1,
    dia: "Lunes",
    aula: "Aula 01",
    horaInicio: "7:30 a.m",
    horaFinal: "9:30 a.m",
    nivel: "B1",
    grupo: "02",
    clase: "Pasado continuo y comparación con el pasado simple"
  },
  {
    id: 2,
    dia: "Miércoles",
    aula: "Aula 02",
    horaInicio: "7:30 a.m",
    horaFinal: "9:30 a.m",
    nivel: "B1",
    grupo: "01",
    clase: "Pasado continuo y comparación con el pasado simple"
  },
  {
    id: 3,
    dia: "Jueves",
    aula: "Aula 03",
    horaInicio: "7:30 a.m",
    horaFinal: "9:30 a.m",
    nivel: "B1",
    grupo: "03",
    clase: "Pasado continuo y comparación con el pasado simple"
  },
  {id: 4,
    dia: "Viernes",
    aula: "Aula 01",
    horaInicio: "7:30 a.m",
    horaFinal: "9:30 a.m",
    nivel: "B1",
    grupo: "02",
    clase: "Pasado continuo y comparación con el pasado simple"
  },
  {id: 5,
    dia: "Sábado",
    aula: "Aula 02",
    horaInicio: "7:30 a.m",
    horaFinal: "9:30 a.m",
    nivel: "B1",
    grupo: "01",
    clase: "Pasado continuo y comparación con el pasado simple"
  },
  {id: 6,
    dia: "Martes",
    aula: "Aula 03",
    horaInicio: "7:30 a.m",
    horaFinal: "9:30 a.m",
    nivel: "B1",
    grupo: "03",
    clase: "Pasado continuo y comparación con el pasado simple"
  },
  {id: 7,
    dia: "Lunes",
    aula: "Aula 01",
    horaInicio: "9:30 a.m",
    horaFinal: "11:30 a.m",
    nivel: "B1",
    grupo: "02",
    clase: "Pasado continuo y comparación con el pasado simple"
  },
  {id: 8,
    dia: "Miércoles",
    aula: "Aula 02",
    horaInicio: "9:30 a.m",
    horaFinal: "11:30 a.m",
    nivel: "B1",
    grupo: "01",
    clase: "Pasado continuo y comparación con el pasado simple"
  },
  {id: 9,
    dia: "Jueves",
    aula: "Aula 03",
    horaInicio: "9:30 a.m",
    horaFinal: "11:30 a.m",
    nivel: "B1",
    grupo: "03",
    clase: "Pasado continuo y comparación con el pasado simple"
  },
  {id: 10,
    dia: "Viernes",
    aula: "Aula 01",
    horaInicio: "9:30 a.m",
    horaFinal: "11:30 a.m",
    nivel: "B1",
    grupo: "02",
    clase: "Pasado continuo y comparación con el pasado simple"
  },
  {id: 11,
    dia: "Sábado",
    aula: "Aula 02",
    horaInicio: "9:30 a.m",
    horaFinal: "11:30 a.m",
    nivel: "B1",
    grupo: "01",
    clase: "Pasado continuo y comparación con el pasado simple"
  },
  {id: 12,
    dia: "Martes",
    aula: "Aula 03",
    horaInicio: "9:30 a.m",
    horaFinal: "11:30 a.m",
    nivel: "B1",
    grupo: "03",
    clase: "Pasado continuo y comparación con el pasado simple"
  }
];

export default info;